# Find the Difference

'''

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

'''

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        diff = set(s)-set(t)
        
        if diff:
            return (list(diff))[0]
        
        d = dict()
        
        for ch in s:
            if ch in d:
                d[ch] = d[ch]+1
            else:
                d[ch]=1
        
        
        for ch in t:
            if ch not in d:
                return ch
            else:
                if d[ch]==1:
                    d.pop(ch)
                else:
                    d[ch] = d[ch]-1
                
class Solution1:
    def findTheDifference(self, s: str, t: str) -> str:
        for l in t:
	        if t.count(l) > s.count(l): return l